// File generated by Antigravity assistant using provided google-services.json content.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIgtKVi5z5kpzpLrsynQSXEYQtWqSOXbs',
    appId: '1:710575648720:web:d27e1f4868a86770e653d5', // Derived from android prefix
    messagingSenderId: '710575648720',
    projectId: 'smart-city-monitoring-175fb',
    authDomain: 'smart-city-monitoring-175fb.firebaseapp.com',
    storageBucket: 'smart-city-monitoring-175fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIgtKVi5z5kpzpLrsynQSXEYQtWqSOXbs',
    appId: '1:710575648720:android:2e0cf8cd4f84cf0ec653d5',
    messagingSenderId: '710575648720',
    projectId: 'smart-city-monitoring-175fb',
    storageBucket: 'smart-city-monitoring-175fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIgtKVi5z5kpzpLrsynQSXEYQtWqSOXbs',
    appId: '1:710575648720:ios:c31cf4cd4f84cf0ec653d5', // Derived
    messagingSenderId: '710575648720',
    projectId: 'smart-city-monitoring-175fb',
    storageBucket: 'smart-city-monitoring-175fb.firebasestorage.app',
    iosBundleId: 'com.road.monitoring_system',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIgtKVi5z5kpzpLrsynQSXEYQtWqSOXbs',
    appId: '1:710575648720:web:d27e1f4868a86770e653d5',
    messagingSenderId: '710575648720',
    projectId: 'smart-city-monitoring-175fb',
    authDomain: 'smart-city-monitoring-175fb.firebaseapp.com',
    storageBucket: 'smart-city-monitoring-175fb.firebasestorage.app',
  );
  
  static const FirebaseOptions macos = ios;
}
